{% set name = "doit" %}
{% set version = "0.31.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fd359786639a2230701c8875d5821a2b78e0e01fd70623ae1edf62b708c83e6c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [py2k]
  entry_points:
    - doit = doit.__main__:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cloudpickle
    - macfsevents  # [osx]
    - pyinotify  # [linux]

test:
  imports:
    - doit
  commands:
    - doit --help

about:
  home: http://pydoit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: doit - Automation Tool
  description: "
    `doit` is a task management & automation tool.

    `doit` comes from the idea of bringing the power of build-tools to execute
    any kind of **task**

    `doit` is a modern open-source build-tool written in python designed to be
    simple to use and flexible to deal with complex work-flows.

    It is specially suitable for building and managing custom work-flows where
    there is no out-of-the-box solution available. 
    
    `doit` has been successfully used on: systems test/integration automation,
    scientific computational pipelines, content generation, configuration
    management, etc."
  doc_url: 'http://pydoit.org/contents.html'
  dev_url: 'https://github.com/pydoit/doit'

extra:
  recipe-maintainers:
    - pbronez
