{% set name = "doit" %}
{% set version = "0.32.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 323d0411e50a0babb945e2a639aa6e633fbb84a9f98086df0c880e739237750c

build:
  number: 0
  skip: true  # [py<34]
  entry_points:
    - doit = doit.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
  run:
    - cloudpickle
    - python
    - macfsevents  # [osx]
    - pyinotify  # [linux]

# we don't ship the src dodo.py file
{% set skips = ["test_execute"] %}

# appears fixed on py38
{% set skips = skips + ["test_not_picklable_raises_InvalidTask"] %}  # [py>37]

# hangs on osx CI
{% set skips = skips + ["testLoop"] %}  # [osx]

# fails on win CI with perms errors, etc.
{% set skips = skips + ["test_dump", "test_remove_from_non_empty_file", "test_unicode_string"] %}  # [win]

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=4.0
  imports:
    - doit
  commands:
    - python -m pip check
    - doit --version
    - doit --help
    - pytest -vv -k "not ({{ skips | join(' or ') }})"

about:
  home: https://pydoit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: doit - Automation Tool
  description: |
    `doit` is a task management & automation tool.

    `doit` comes from the idea of bringing the power of build-tools to execute
    any kind of **task**

    `doit` is a modern open-source build-tool written in python designed to be
    simple to use and flexible to deal with complex work-flows.

    It is specially suitable for building and managing custom work-flows where
    there is no out-of-the-box solution available.

    `doit` has been successfully used on: systems test/integration automation,
    scientific computational pipelines, content generation, configuration
    management, etc."
  doc_url: https://pydoit.org/contents.html
  dev_url: https://github.com/pydoit/doit
  doc_source_url: https://github.com/pydoit/doit/tree/{{ version }}/doc

extra:
  recipe-maintainers:
    - pbronez
    - bollwyvl
